Organizations:

    - &Authority1

        Name: Authority1
        ID: Authority1
        MSPDir: crypto-config/authorities/authority1.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Authority1.member')"
            Writers:
                Type: Signature
                Rule: "OR('Authority1.member')"
            Admins:
                Type: Signature
                Rule: "OR('Authority1.admin')"

    - &Institution1

        Name: Institution1
        ID: Institution1
        MSPDir: crypto-config/institutions/institution1.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('Institution1.admin', 'Institution1.peer', 'Institution1.client')"
            Writers:
                Type: Signature
                Rule: "OR('Institution1.admin', 'Institution1.client')"
            Admins:
                Type: Signature
                Rule: "OR('Institution1.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('Institution1.peer')"

        AnchorPeers:
            - Host: peer0.institution1.com
              Port: 7051

Capabilities:

    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true

Application: &ApplicationDefaults

    Organizations:


    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"

    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults

    OrdererType: solo

    Addresses:
        - authority1.com:7050

    BatchTimeout: 2s

    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092

    Organizations:


    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    OneOrgOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *Authority1
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Institution1

    OneOrgChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Institution1
            Capabilities:
                <<: *ApplicationCapabilities
