OrdererOrgs:
  - Name: MainAuthorityOrderer
    Domain: mainauthority.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost

PeerOrgs:
  - Name: MainAuthorityInstitution
    Domain: institution.mainauthority.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
  - Name: MainAuthorityApplicant
    Domain: applicant.mainauthority.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
    Users:
      Count: 1
