OrdererOrgs:
  - Name: MainAuthorityOrderer
    Domain: mainauthority.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: MainAuthorityInstitution
    Domain: institution.mainauthority.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
  - Name: MainAuthorityApplicant
    Domain: applicant.mainauthority.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 0
