version: '2'

volumes:

  orderer.mainauthority.com:

  peer0.institution.mainauthority.com:

  peer0.applicant.mainauthority.com:

networks:

  byfn:

services:

  orderer.mainauthority.com:
    extends:
      file: base/docker-compose-base.yaml
      service: orderer.mainauthority.com
    container_name: orderer.mainauthority.com
    networks:
      - byfn

  peer0.institution.mainauthority.com:
    container_name: peer0.institution.mainauthority.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.institution.mainauthority.com
    networks:
      - byfn

  peer0.applicant.mainauthority.com:
    container_name: peer0.applicant.mainauthority.com
    extends:
      file: base/docker-compose-base.yaml
      service: peer0.applicant.mainauthority.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.institution.mainauthority.com:7051
      - CORE_PEER_LOCALMSPID=MainAuthorityInstitutionMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/users/Admin@institution.mainauthority.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.mainauthority.com
      - peer0.institution.mainauthority.com
      - peer0.applicant.mainauthority.com
    networks:
      - byfn
