version: '3.7'

volumes:
  orderer.mainauthority.com:
  peer0.institution.mainauthority.com:
  peer0.applicant.mainauthority.com:

networks:
  rrs:

services:

  orderer.mainauthority.com:
    container_name: orderer.mainauthority.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=file
      - ORDERER_GENERAL_BOOTSTRAPFILE=/var/hyperledger/orderer/orderer.sys-channel.block
      - ORDERER_GENERAL_LOCALMSPID=MainAuthorityOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/sys-channel.block:/var/hyperledger/orderer/orderer.sys-channel.block
      - ./crypto-config/ordererOrganizations/mainauthority.com/orderers/orderer.mainauthority.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/mainauthority.com/orderers/orderer.mainauthority.com/tls:/var/hyperledger/orderer/tls
      - orderer.mainauthority.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      - rrs

  peer0.institution.mainauthority.com:
    container_name: peer0.institution.mainauthority.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=reliable-resume-system_rrs
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer0.institution.mainauthority.com
      - CORE_PEER_ADDRESS=peer0.institution.mainauthority.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.institution.mainauthority.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.institution.mainauthority.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.institution.mainauthority.com:8051
      - CORE_PEER_LOCALMSPID=MainAuthorityInstitutionMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls:/etc/hyperledger/fabric/tls
      - peer0.institution.mainauthority.com:/var/hyperledger/production
    depends_on:
      - orderer.mainauthority.com
    ports:
      - 8051:8051
    networks:
      - rrs

  peer0.applicant.mainauthority.com:
    container_name: peer0.applicant.mainauthority.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=reliable-resume-system_rrs
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer0.applicant.mainauthority.com
      - CORE_PEER_ADDRESS=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.applicant.mainauthority.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_LOCALMSPID=MainAuthorityApplicantMSP
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/applicant.mainauthority.com/peers/peer0.applicant.mainauthority.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/applicant.mainauthority.com/peers/peer0.applicant.mainauthority.com/tls:/etc/hyperledger/fabric/tls
      - peer0.applicant.mainauthority.com:/var/hyperledger/production
    depends_on:
      - orderer.mainauthority.com
    ports:
      - 9051:9051
    networks:
      - rrs

  init.mainauthority.com:
    container_name: init.mainauthority.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=reliable-resume-system_rrs
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: sh /etc/scripts/peer-init.sh
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/etc/crypto-config
      - peer0.applicant.mainauthority.com:/var/hyperledger/production
      - ./channel-artifacts:/etc/channel-artifacts
      - ./chaincode:/etc/chaincode
      - ./scripts:/etc/scripts
    depends_on:
      - peer0.institution.mainauthority.com
      - peer0.applicant.mainauthority.com
    networks:
      - rrs

  ca.mainauthority.com:
    container_name: ca.mainauthority.com
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/ordererOrganizations/mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ./ca/mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    networks:
      - rrs

  ca.institution.mainauthority.com:
    container_name: ca.institution.mainauthority.com
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/institution.mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ./ca/institution.mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 8054:8054
    networks:
      - rrs

  ca.applicant.mainauthority.com:
    container_name: ca.applicant.mainauthority.com
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/applicant.mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ./ca/applicant.mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 9054:9054
    networks:
      - rrs

  client.applicant.mainauthority.com:
    container_name: client.applicant.mainauthority.com
    image: node:12
    environment:
      - NODE_ENV=production
      - PORT=9443
      - HOST=0.0.0.0
      - TLS_CERT_FILE=/var/run/rrs/crypto-config/peerOrganizations/applicant.mainauthority.com/tlsca/tlsca.applicant.mainauthority.com-cert.pem
      - TLS_KEY_FILE=/var/run/rrs/crypto-config/peerOrganizations/applicant.mainauthority.com/tlsca/priv_sk
      - CCP_PATH=/var/run/rrs/ccp/ccp.applicant.mainauthority.com.json
      - WALLET_PATH=/var/run/rrs/wallet
      - CA_URL=https://ca.applicant.mainauthority.com:9054
      - MSP_ID=MainAuthorityApplicantMSP
      - USER_ID=admin
      - USER_SECRET=adminpw
    working_dir: /var/run/rrs/client
    command: sh -c "npm install && node index"
    volumes:
      - ./client:/var/run/rrs/client
      - ./wallet:/var/run/rrs/wallet
      - ./ccp:/var/run/rrs/ccp
      - ./crypto-config:/var/run/rrs/crypto-config
    depends_on:
      - init.mainauthority.com
      - ca.applicant.mainauthority.com
    ports:
      - 9443:9443
    networks:
      - rrs

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=reliable-resume-system_rrs
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.institution.mainauthority.com
      - CORE_PEER_ADDRESS=peer0.institution.mainauthority.com:7051
      - CORE_PEER_LOCALMSPID=MainAuthorityInstitutionMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.institution.mainauthority.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.institution.mainauthority.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.institution.mainauthority.com:8051
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/institution.mainauthority.com/users/Admin@institution.mainauthority.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - peer0.institution.mainauthority.com:/var/hyperledger/production
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincode
    depends_on:
      - init.mainauthority.com
      - ca.institution.mainauthority.com
    ports:
      - 8053:8051
    networks:
      - rrs
