version: '2'

services:

  orderer.mainauthority.com:
    container_name: orderer.mainauthority.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/mainauthority.com/orderers/orderer.mainauthority.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/mainauthority.com/orderers/orderer.mainauthority.com/tls:/var/hyperledger/orderer/tls
      - orderer.mainauthority.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.institution.mainauthority.com:
    container_name: peer0.institution.mainauthority.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.institution.mainauthority.com
      - CORE_PEER_ADDRESS=peer0.institution.mainauthority.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.institution.mainauthority.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.institution.mainauthority.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.institution.mainauthority.com:8051
      - CORE_PEER_LOCALMSPID=MainAuthorityInstitutionMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/institution.mainauthority.com/peers/peer0.institution.mainauthority.com/tls:/etc/hyperledger/fabric/tls
      - peer0.institution.mainauthority.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.applicant.mainauthority.com:
    container_name: peer0.applicant.mainauthority.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.applicant.mainauthority.com
      - CORE_PEER_ADDRESS=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.applicant.mainauthority.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.applicant.mainauthority.com:9051
      - CORE_PEER_LOCALMSPID=MainAuthorityApplicantMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/applicant.mainauthority.com/peers/peer0.applicant.mainauthority.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/applicant.mainauthority.com/peers/peer0.applicant.mainauthority.com/tls:/etc/hyperledger/fabric/tls
      - peer0.applicant.mainauthority.com:/var/hyperledger/production
    ports:
      - 9051:9051

  ca.mainauthority.com:
    container_name: ca.mainauthority.com
    extends:
      file: ca-base.yaml
      service: ca-base
    volumes:
      - ../crypto-config/ordererOrganizations/mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ../ca/mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054

  ca.institution.mainauthority.com:
    container_name: ca.institution.mainauthority.com
    extends:
      file: ca-base.yaml
      service: ca-base
    volumes:
      - ../crypto-config/peerOrganizations/institution.mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ../ca/institution.mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 8054:8054

  ca.applicant.mainauthority.com:
    container_name: ca.applicant.mainauthority.com
    extends:
      file: ca-base.yaml
      service: ca-base
    volumes:
      - ../crypto-config/peerOrganizations/applicant.mainauthority.com/ca:/etc/hyperledger/fabric-ca-server-config
      - ../ca/applicant.mainauthority.com:/etc/hyperledger/fabric-ca-server
    ports:
      - 9054:9054
